---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : majoral
production_url : http://aikido.majoral.es

posts:
  permalink: /:title/
  summary_lines: 3
  latest: 5

pages:
  permalink: 'pretty'