title : Pere Majoral 
tagline: Pere Majoral 
url: http://aikido.majoral.es
author :
  name : Pere Majoral
  email : pere@majoral.es
  github : majoral
  twitter : peremajoral
  feedburner : peremajoral
  gravatar: bbe4f374067b9f82efddc49721f3151d

navigation :
  - blog.html
  - acerca.md
  - contacto.md
  
plugins:
  sitemap_generator: # all optional
    file_name: sitemap.xml
    exclude_id:
      - search.html
      - pages.html
    change_frequency_custom_name: changefreq
    priority_custom_variable_name: priority